services:
  database:
    container_name: get_m3u_content_db
    image: postgres:16.0-alpine3.18
    env_file:
      - .env
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-m3u_content}
      - POSTGRES_USER=${POSTGRES_USER:-local_user}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  m3u_consumer:
    build: .
    container_name: m3u_consumer
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-local_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-m3u_content}
    volumes:
      - .:/app
